[lib]
crate-type = ["cdylib", "lib"]

[package]
name = "abi-wrapper"
version = "1.0.0"
edition = "2021"

[features]
mainnet = []
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"
zeta-abi = "0.1.1"