name: Program

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  NODE_VERSION: "16.13.0"
  SOLANA_VERSION: "1.14.12"
  ANCHOR_VERSION: "0.26.0"

jobs:
  build:
    name: Build program and test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        name: Checkout source
      - uses: actions/cache@v3
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-v0000-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v3
        name: Cache Solana Tool Suite
        id: cache_solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-v0001-${{ env.SOLANA_VERSION }}
      - uses: actions-rs/toolchain@v1
        if: steps.cache_solana.outputs.cache-hit != 'true'
        name: Install Rust toolchain
        with:
          profile: minimal
          toolchain: stable
      - run: rustup component add rustfmt clippy
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          architecture: x64
      - name: Setup Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${SOLANA_VERSION}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          echo "[2,48,202,144,253,109,253,181,3,217,88,73,28,214,141,101,174,166,99,103,156,216,118,62,78,245,215,142,139,81,62,98,54,93,226,165,249,36,9,214,52,186,160,5,225,80,252,163,26,19,55,186,179,46,254,235,159,248,7,136,216,207,47,148]" > /home/runner/.config/solana/id.json
      - name: Setup Anchor dependencies
        shell: bash
        run: |
          npm i -g @project-serum/anchor-cli@v${ANCHOR_VERSION}
      - name: Build zeta-abi
        run: cargo build
      - name: Build abi-wrapper
        run: |
          rustup install 1.70.0
          rustup default 1.70.0
          rustc --version
          cd abi-wrapper && anchor build --skip-lint
